"""Initial migration

Revision ID: 43e77d735271
Revises: 
Create Date: 2026-06-30 23:14:31.835486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e77d735271'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('invalid_trash_bin_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bin_id', sa.String(length=50), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin_id', 'event_time', name='uq_invalid_event')
    )
    op.create_table('valid_trash_bin_events',
    sa.Column('bin_id', sa.String(length=50), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('fill_level', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bin_id', 'event_time')
    )
    op.create_table('ward_bins',
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ward', 'bin_id')
    )
    op.create_table('ward_fill_level_agg',
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_fill_level', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ward', 'window_start', 'window_end')
    )
    op.create_table('ward_fill_level_risk_agg',
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_fill_level', sa.Float(), nullable=False),
    sa.Column('max_fill_level', sa.Integer(), nullable=False),
    sa.Column('min_fill_level', sa.Integer(), nullable=False),
    sa.Column('bins_above_80', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ward', 'window_start', 'window_end')
    )
    op.execute("""
    CREATE OR REPLACE VIEW ward_latest_fill_level AS
    SELECT DISTINCT ON (ward)
        ward,
        window_start,
        window_end,
        avg_fill_level
    FROM ward_fill_level_agg
    ORDER BY ward, window_end DESC;
    """)
    op.execute("""
    INSERT INTO api_users (username, password_hash, role, is_active)
    VALUES
      ('admin', '$2b$12$Zo26K4rwepjeP4x.p.aTeusjacVJqdEuEOw4vuf4sTYEqkeSbcEBq', 'admin', TRUE),
      ('viewer', '$2b$12$nDocjJJwQ9ps4W6q4MZ8MO1.X41C9VbMt/GG6ml.PIuPvw77Du3WS', 'viewer', TRUE)
    ON CONFLICT (username) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS ward_latest_fill_level;")
    op.drop_table('ward_fill_level_risk_agg')
    op.drop_table('ward_fill_level_agg')
    op.drop_table('ward_bins')
    op.drop_table('valid_trash_bin_events')
    op.drop_table('invalid_trash_bin_events')
    op.drop_table('api_users')
    # ### end Alembic commands ###
